export const TextConstants = {
  SEARCH: 'Search',
  ADD: 'Add new worker',
  EDIT: 'Edit the worker',
  DONE: 'Done',
  CANCEL: 'Cancel',
  NAME: 'Name: ',
  BIRTHDAY: 'Birthday: ',
  POSITION: 'Position: ',
  SALARY: 'Salary: ',
  SELECTDATE: 'select date',
  FORMATDATE: 'YYYY-MM-DD',
  MINDATE: '1940-01-01',
  MAXDATE: '2000-01-01',
  FILLALLTHEFIELDS: 'Please, fill all the fields!',
  TITLEAPP: 'WorkersList: MERN, redux-thunk',
  PLEASEWAIT: 'Please wait while data is loading',
  SERVETNOTRESP: 'Sorry, the server is not responding now! Try later!',
  WORKEREDITED: 'The worker has been edited!',
  WORKERDELETED: 'Worker has been deleted',
  NEWWORKERADDED: 'New worker has been added!',
  WORKERALREADYADDED: 'This worker has been already added!',
  TRYAGAIN: 'Try again'
}
